/* 
이론과제 3일차

Q3-1
(1) 원자성
(2) 완전 함수적 종속
(3) 이행적 종속 제거

Q3-2
(1) 제3정규화
(2) 제2정규화

Q3-3
(1) inner join
(2) left join
(3) right join
(4) outer join

Q3-4
(1) 반정규화

Q3-5
(1) 인덱스
(2) 인덱스
(3) 인덱스
(4) 인덱

Q3-6
(1) 트랜잭션
(2) Atomicity(원자성), 
(3)Consistency(일관성)
 */



/* 실습과제 1번*/
CREATE TABLE DEPT_TEST AS SELECT * FROM DEPT
SELECT * FROM DEPT;
ALTER TABLE DEPT_TEST MODIFY RELATED_CERT VARCHAR2(20) NULL;
ALTER TABLE DEPT_TEST ADD LOC VARCHAR(20);
ALTER TABLE DEPT_TEST RENAME COLUMN DEPARTMENT_NAME TO DNAME;
ALTER TABLE DEPT_TEST RENAME COLUMN DEPARTMENT_ID TO DEPTNO;


INSERT INTO DEPT_TEST(DEPTNO, DNAME, LOC) VALUES(50, 'ORACLE', 'BUSAN');
INSERT INTO DEPT_TEST(DEPTNO, DNAME, LOC) VALUES(60, 'SQL', 'ILSAN');
INSERT INTO DEPT_TEST(DEPTNO, DNAME, LOC) VALUES(70, 'SELECT', 'INCHEON')
INSERT INTO DEPT_TEST(DEPTNO, DNAME, LOC) VALUES(80, 'DML', 'BUNDANG');




/* 실습과제 222 2번*/
CREATE TABLE EMP_TEST AS SELECT * FROM EMP

SELECT * FROM EMP_TEST

INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES (7201, 'TEST_USER1', 'MANAGER', 7788, TO_DATE('2016-01-02 00:00:00', 'YYYY-DD-MM HH24:MI:SS'), 4500, 0, 20)
INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES (7202, 'TEST_USER2', 'CLERK', 7201, TO_DATE('2016-02-21 00:00:00', 'YYYY-DD-MM HH24:MI:SS'), 1800, 0, 10)
INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)VALUES (7203, 'TEST_USER3', 'ANALYST', 7201, TO_DATE('2016-04-11 00:00:00', 'YYYY-DD-MM HH24:MI:SS'), 3400, 0, 30)
INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)VALUES (7204, 'TEST_USER4', 'SALESMAN', 7201, TO_DATE('2016-05-31 00:00:00', 'YYYY-DD-MM HH24:MI:SS'), 2700, 0, 40)
INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)VALUES (7205, 'TEST_USER5', 'CLERK', 7201, TO_DATE('2016-07-20 00:00:00', 'YYYY-DD-MM HH24:MI:SS'), 2600, 0, 50 )
INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)VALUES (7206, 'TEST_USER6', 'CLERK', 7201, TO_DATE('2016-09-08 00:00:00', 'YYYY-DD-MM HH24:MI:SS'), 2600, 0, 60)
INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)VALUES (7207, 'TEST_USER7', 'LECTURER', 7201, TO_DATE('2016-10-28 00:00:00', 'YYYY-DD-MM HH24:MI:SS'), 2300, 0, 70)
INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)VALUES (7208, 'TEST_USER8', 'STUDENT', 7201, TO_DATE('2018-03-09 00:00:00', 'YYYY-DD-MM HH24:MI:SS'), 1200, 0, 80)

/* 실습과제 223 3번*/
UPDATE EMP_TEST
SET DEPTNO = 70 
WHERE SAL > (SELECT AVG(SAL)
FROM EMP_TEST WHERE DEPTNO = 50);





*-- 4번 문제
UPDATE EMP_TEST
SET DEPTNO = 80, SAL = SAL * 1.2
WHERE (DEPTNO, SAL) IN 
      (SELECT DEPTNO, SAL
        FROM (SELECT ROWNUM AS RN, DEPTNO, SAL
        FROM (SELECT DEPTNO, SAL
                FROM EMP_TEST
                WHERE DEPTNO = 60
                ORDER BY HIREDATE))
                WHERE RN > 1)

                
                
/* 실습과제 228 1번 */
CREATE TABLE EMP_USER (
    EMPNO NUMBER(5),
    ENAME VARCHAR2(20),
    JOB VARCHAR2(10),
    MGR NUMBER(5),
    HIREDATE DATE,
    SAL NUMBER(7,2),
    DEPTNO NUMBER
)

/* 실습과제 228 2번 */
ALTER TABLE EMP_USER ADD RESIGN_DATE DATE
ALTER TABLE EMP_USER ADD DAY_DATE DATE

/* 실습과제 228 3번 */
ALTER TABLE EMP_USER ADD SUR_NAME CHAR(5)

/* 실습과제 228 4번 */
ALTER TABLE EMP_USER MODIFY SUR_NAME CHAR(10)

/* 실습과제 228 5번 */
ALTER TABLE EMP_USER RENAME COLUMN ENAME TO FULL_NAME



/* 실습과제 249 1번 */
CREATE TABLE EMP_IDX AS SELECT * FROM EMP
CREATE INDEX EMP_EMPNO_IDX ON EMP_IDX(EMPNO)
\


/* 실습과제 249 2번 */
SELECT INDEX_NAME, TABLE_NAME, TABLESPACE_NAME
FROM USER_INDEXES
WHERE TABLE_NAME = 'EMP_IDX'

SELECT * FROM EMP_IDX

/* 실습과제 249 3번 */
CREATE VIEW VW_EMP_IDX
AS (SELECT EMPNO, ENAME, JOB, DEPTNO, SAL, CASE WHEN COMM IS NOT NULL THEN 'Y' ELSE 'N' END AS COMM
        FROM EMP_IDX
        WHERE SAL >= 2000)
SELECT * FROM VW_EMP_IDX



/* 실습과제 242 이론문제
 1. 제약조건
 2. UNIQUE
 3. NOT NULL
 4. PRIMARY KEY
 5. 외래키
 */